### ISSUE TITLE
Clamping show part of next line with certain fonts (Roboto via Google Fonts)

### ISSUE THREAD

**Issue by shawnwildermuth** [tailwindlabs/tailwindcss-line-clamp#20]
### What version of @tailwindcss/line-clamp are you using?

0.4.0

### What version of Node.js are you using?

v16.15.0

### What browser are you using?

msedge, chrome (not seen in Firefox)

### What operating system are you using?

Win11

### Reproduction repository

https://github.com/shawnwildermuth/repolineclamp

### Describe your issue

When I use clamping (e.g. line-clamping-2), I show the top of the first masked line:

![image](https://user-images.githubusercontent.com/568272/168564143-4a31e702-6cfe-4704-87f3-c8a7a2948708.png)

Example of the container for the clamping:

```
<p class="text-sm p-1 line-clamp-2 md:line-clamp-none">${film.overview}</p>
```

Only seems to happen at 100% zoom. Any way to tweak the line length to solve this?

**Comment by adamwathan** [comment]
Hey! This is because you have padding on the same element that has line-clamp which sort of unhides the clamped text. If you make sure to put the padding on a separate element you get the result you want:

https://play.tailwindcss.com/OrueoIY5gn

Nothing Tailwind-specific here I'm afraid, same thing happens with just vanilla CSS 👍

**Comment by shawnwildermuth** [comment]
Thanks!
