### ISSUE TITLE
There is a bug when used in React

### ISSUE THREAD

**Issue by kevinalfito69** [tailwindlabs/tailwindcss-line-clamp#21]
### What version of @tailwindcss/line-clamp are you using?

v0.4.0

### What version of Node.js are you using?

v16.16.0

### What browser are you using?

Edge

### What operating system are you using?

Windows 11

### Reproduction repository

https://github.com/kevinalfito69/React-blog

### Describe your issue

![image](https://user-images.githubusercontent.com/71138490/184493148-e9ab8c05-9428-478d-bb84-a24e347e62c4.png)

**Comment by thecrypticace** [comment]
Hey! So after a bit of poking around I found out that this is a bug in both Safari and Chrome :(

The workaround here is to **not** add padding to an element with line-clamp on it but on a parent element instead: https://play.tailwindcss.com/NAgq8jI34p

Going to close since unfortunately nothing we can do about this on our end, just a browser thing you have to work around :(
