### ISSUE TITLE
Display issue on ios

### ISSUE THREAD

**Issue by Wulfheart** [tailwindlabs/tailwindcss-line-clamp#7]
### What version of @tailwindcss/line-clamp are you using?

0.2.0

### What version of Node.js are you using?

12.19.0

### What browser are you using?

Safari, Firefox

### What operating system are you using?

Manjaro Linux, iOS

### Reproduction repository

https://play.tailwindcss.com/UHz7irJniZ

### Describe your issue

Given the reproduction repository:
On FIrefox it looks as expected:
![image](https://user-images.githubusercontent.com/25671390/120070892-0151ec80-c08d-11eb-8a7c-0d3397266315.png)

On my iPhone it looks like this:
![image](https://user-images.githubusercontent.com/25671390/120070915-1a5a9d80-c08d-11eb-9300-3d25373ff57f.png)

**Comment by adamwathan** [comment]
Hey! This appears to just be the nature of how this CSS feature behaves in Safari — it looks like it does weird things when you apply it to an element that has block-level children. Same thing happens with vanilla CSS and not using Tailwind at all.

Hard to know for sure what the right workaround is in your situation but you can see here it behaves as expected in Safari if applied directly to the element containing the text:

https://play.tailwindcss.com/lh6UN4RKJq

Going to close since unfortunately nothing we can do about this on our end, just a browser thing you have to work around :(

**Comment by Wulfheart** [comment]
Thank you!

**Comment by draskog** [comment]
Is it possible to implement a custom plugin and add css attribute **max-width = number of lines * current line-height** 
not sure how to get the current line-height value of the element in the plugin

`const currentLineHeight = 1.5;`

`overflow: 'hidden',`
`display: '-webkit-box',`
`'-webkit-box-orient': 'vertical',`
`'-webkit-line-clamp': ${value},`
`'max-height': ${value * currentLineHeight}rem`
